#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -o split.out
#$ -e que.err
#$ -j y
#$ -r y
#$ -q honda
#$ -pe honda 1
hostname
date

export plop_script=/home/yjcheng/handbook/2-Good-practices-in-research/Docking/PLOP-rescore-DOCK3.7-results/zhouyu_rescore   # need to be changed
export plop_path=/home/soft/plop/6.0   # need to be changed
export plop_data=/home/soft/plop/6.0/data
export mol2_script=/home/yjcheng/handbook/2-Good-practices-in-research/Docking/PLOP-rescore-DOCK3.7-results  # need to be changed
export LD_LIBRARY_PATH=$plop_path:$LD_LIBRARY_PATH

# env=`pwd`
# 1. To generate small molecule parameters 

$mol2_script/mol_split.pl poses.mol2 250 ligand_pose 2>> que.err
# /home/yjcheng/dock3.7/dock_template/2_PLOP_rescore/para_gen_opls2005.pl ligand_pose poses.mol2 honda . 250

cd ligand_pose/mol_tmp

ls |grep decoys |while read line 
do
cd $line 
qsub /home/yjcheng/dock3.7/dock_template/2_PLOP_rescore/split_qsub.sh
cd ..
done 
 
# /home/yjcheng/dock3.7/zj/2OV5/dock_tool_test/para_gen_opls2005.pl ligand_pose poses.mol2 honda . 250
